// Generated by ts-to-zod
import { z } from "zod";

const dictionaryExampleTypeSchema = z.any();

const audioRecordTypeSchema = z.any();

export const dictionaryEntryTypeSchema = z.object({
    id: z.uuid(),
    text: z.string().min(1, "Text is required"),
    transcription: z.string().min(1, "Transcription is required"),
    pronounceVideoLinks: z.array(z.string()),
    examples: z.array(dictionaryExampleTypeSchema),
    audioRecords: z.array(audioRecordTypeSchema),
    createdAt: z.iso.datetime(),
    updatedAt: z.iso.datetime()
});
