/**
 * Automatically generated by script.
 * DO NOT EDIT MANUALLY. Use: ./scripts/generate-zod-config.sh
 */
export default [
  {
    name: 'flashcard',
    input: 'src/assistant/flashcards/interfaces/flashcard.interface.ts',
    output: 'src/assistant/flashcards/schemas/flashcard.schema.ts',
  },
  {
    name: 'dictionaryExample',
    input:
      'src/assistant/dictionary-examples/interfaces/dictionary-example.interface.ts',
    output:
      'src/assistant/dictionary-examples/schemas/dictionary-example.schema.ts',
  },
  {
    name: 'audioRecord',
    input: 'src/assistant/audio-records/interfaces/audio-record.interface.ts',
    output: 'src/assistant/audio-records/schemas/audio-record.schema.ts',
  },
  {
    name: 'dictionaryEntry',
    input:
      'src/assistant/dictionary-entries/interfaces/dictionary-entry.interface.ts',
    output:
      'src/assistant/dictionary-entries/schemas/dictionary-entry.schema.ts',
  },
];
