// Generated by ts-to-zod
import { z } from "zod";

export const dictionaryExampleTypeSchema = z.object({
    id: z.uuid(),
    example: z.string().min(1, "Example is required"),
    translation: z.string().min(1, "Translation is required"),
    accent: z.string().min(1, "Accent is required"),
    accentTranslation: z.string().min(1, "Accent translation is required"),
    accentTranscription: z.string().min(1, "Accent transcription is required"),
    dictionaryEntryId: z.uuid(),
    createdAt: z.iso.datetime(),
    updatedAt: z.iso.datetime()
});
