// Generated by ts-to-zod
import { z } from "zod";

export const chunkTypeSchema = z.object({
  id: z.uuid(),
  text: z.string().min(1, "Text cannot be empty."),
  lang: z.string().min(2).max(10),
  createdAt: z.iso.datetime(),
  updatedAt: z.iso.datetime(),
});

export const createChunkTypeSchema = z.object({
  text: z.string().min(1, "Text cannot be empty."),
  lang: z.string().min(2).max(10).optional(),
});

export const createChunksBodyTypeSchema = z.object({
  chunks: z.array(createChunkTypeSchema),
});
