// Generated by ts-to-zod
import { z } from "zod";

export const knowledgeLevelSchema = z.union([z.literal("junior"), z.literal("middle"), z.literal("senior")]);

export const usageContextSchema = z.union([z.literal("interview"), z.literal("general-knowledge"), z.literal("best-practice"), z.literal("deep-dive")]);

export const flashcardTypeSchema = z.object({
    id: z.uuid(),
    question: z.string().min(1, "Question cannot be empty."),
    answer: z.string().min(1, "Answer cannot be empty."),
    sourceUrl: z.url(),
    tags: z.array(z.string()),
    level: knowledgeLevelSchema,
    contexts: z.array(usageContextSchema),
    createdAt: z.iso.datetime(),
    updatedAt: z.iso.datetime()
});
