import { applyDecorators } from '@nestjs/common';
import { ApiProperty } from '@nestjs/swagger';
import {
  IsString,
  IsNotEmpty,
  IsArray,
  ArrayMinSize,
  IsUrl,
  IsUUID,
  IsDateString,
  IsEnum,
} from 'class-validator';

export function TitleProperty() {
  return applyDecorators(
    ApiProperty({
      description:
        'Title of the article from which the flashcard is generated.',
      example: 'Geography of France',
    }),
    IsString(),
    IsNotEmpty(),
  );
}

export function ChunksProperty() {
  return applyDecorators(
    ApiProperty({
      description: 'Chunks of text used to generate the flashcard question.',
      example: ['capital of France', 'largest city in France'],
    }),
    IsArray(),
    ArrayMinSize(1),
    IsString({ each: true }),
    IsNotEmpty({ each: true }),
  );
}

export function SourceUrlProperty() {
  return applyDecorators(
    ApiProperty({
      description: 'Source URL when the data were copied',
      example: 'https://example.com/geography/france',
    }),
    IsUrl(),
  );
}

export function IdProperty() {
  return applyDecorators(
    ApiProperty({
      description: 'The unique identifier for the flashcard.',
      example: 'a1b2c3d4-e5f6-7890-1234-567890abcdef',
    }),
    IsUUID(),
  );
}

export function QuestionProperty() {
  return applyDecorators(
    ApiProperty({
      description: 'The question part of the flashcard, generated by AI.',
      example: 'What is the main difference between `let` and `var`?',
      required: false,
    }),
    IsString(),
    IsNotEmpty(),
  );
}

export function AnswerProperty() {
  return applyDecorators(
    ApiProperty({
      description: 'The answer part of the flashcard, generated by AI.',
      example: '`let` is block-scoped, while `var` is function-scoped.',
      required: false,
    }),
    IsString(),
    IsNotEmpty(),
  );
}

export function ContextProperty() {
  return applyDecorators(
    ApiProperty({
      description: 'Context identifier for the flashcard (1-2 words max).',
      example: 'JavaScript',
      maxLength: 50,
      required: false,
    }),
    IsString(),
    IsNotEmpty(),
  );
}

export function TagsProperty() {
  return applyDecorators(
    ApiProperty({
      description: 'An array of tags related to the flashcard content.',
      type: [String],
      example: ['javascript', 'es6', 'scope'],
    }),
    IsArray(),
    IsString({ each: true }),
  );
}

export function LevelProperty() {
  const levels = ['junior', 'middle', 'senior', '-'];
  return applyDecorators(
    ApiProperty({
      description: 'The estimated knowledge level for the flashcard.',
      example: 'junior',
      enum: levels,
    }),
    IsEnum(levels),
  );
}

export function ContextsProperty() {
  const contexts = [
    'interview',
    'general-knowledge',
    'best-practice',
    'deep-dive',
  ];
  return applyDecorators(
    ApiProperty({
      description: 'Suggested contexts where this knowledge is applicable.',
      type: [String],
      example: ['interview', 'best-practice'],
      enum: contexts,
    }),
    IsArray(),
    IsEnum(contexts, { each: true }),
  );
}

export function CreatedAtProperty() {
  return applyDecorators(
    ApiProperty({
      description: 'The timestamp when the flashcard was created.',
      example: '2025-11-02T10:00:00.000Z',
    }),
    IsDateString(),
  );
}

export function NextReviewDateProperty() {
  return applyDecorators(
    ApiProperty({
      description: 'The next scheduled review date for this flashcard.',
      example: '2025-11-03T10:00:00.000Z',
      type: Date,
      nullable: true,
    }),
    IsDateString(),
  );
}

export function LastIntervalProperty() {
  return applyDecorators(
    ApiProperty({
      description: 'The last interval used for spaced repetition (in days).',
      example: 2,
      nullable: true,
    }),
  );
}

export function UpdatedAtProperty() {
  return applyDecorators(
    ApiProperty({
      description: 'The timestamp when the flashcard was last updated.',
      example: '2025-11-02T10:00:00.000Z',
    }),
    IsDateString(),
  );
}

export function QuestionAudioUrlProperty() {
  return applyDecorators(
    ApiProperty({
      description:
        'The URL of the audio file for the flashcard question stored in Firebase Storage.',
      example:
        'https://firebasestorage.googleapis.com/v0/b/your-app.appspot.com/o/flashcard-questions%2Fa1b2c3d4-e5f6-7890-1234-567890abcdef.mp3?alt=media&token=some-token',
      nullable: true,
    }),
    IsUrl(),
  );
}
